services:
  # Frontend service
  frontend:
    build: 
      context: .
      args:
        - REACT_APP_GEMINI_API_KEY=${REACT_APP_GEMINI_API_KEY}
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - REACT_APP_STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
    container_name: keyword-alchemist-frontend
    ports:
      - "3001:80"
    restart: unless-stopped
    networks:
      - keyword-alchemist-network
    depends_on:
      - backend

  # Backend API service
  backend:
    build: ./backend
    container_name: keyword-alchemist-backend
    ports:
      - "3002:3002"
    restart: unless-stopped
    networks:
      - keyword-alchemist-network
    environment:
      - NODE_ENV=production
      - PORT=3002
      - GEMINI_API_KEY=${REACT_APP_GEMINI_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
    volumes:
      - ./backend/data:/app/data
      - ./backend/credit_system.db:/app/credit_system.db

networks:
  keyword-alchemist-network:
    driver: bridge
